# Instagram account email/username

account_email_or_username: ""

# Instagram account password

account_password: ""


# Accounts we want to invite you must but a space at the end of each account
accounts_to_tag:
  - ""
  - ""
  - ""

# Those are the word needed on the tweet for the bot to comment but we don't need to lookup to comment a comment for those word:
word_list_to_not_check_for_copy:
  - "quelque"
  - "quelque"
  - "quelques"

# Those are the word needed on the tweet for the bot to comment when the tweet ask to comment one thing in particular
word_list_to_check_for_special_comment:
  - "commenter avec"
  - "commentez avec"
  - "commente avec"
  - "commentez"
  - "commenter"
  - "commente"
  - "commentant"
  - "écrit"
  - "dis moi"
  - "dis nous"
  - "dis en commentaire"
  - "dis-moi"
  - "dis-nous"
  - "dit-moi"
  - "dit-nous"
  - "écrivez"
  - "écris"
  - "écrit"
  - "écrire"
  - "dites"
  - "répondez"
  - "réponder"
  - "répondre"
  - "quel"
  - "indiquez nous"
  - "quelle"


# Those are the word needed on the tweet for the bot to comment when the tweet ask to comment random stuff
word_list_to_check_for_comment:
  - "commente"
  - "commentaire"
  - "commentant"
  - "commenter"
  - "commenter le post"
  - "écrit"
  - "écrire"
  - "écrivez"
  - "dites"
  - "dis moi"
  - "dis nous"
  - "dis en commentaire"
  - "dis-moi"
  - "dis-nous"
  - "dit-moi"
  - "dit-nous"
  - "donne nous"
  - "donne le"
  - "répond"
  - "indique"
  - "répondre"
    

# The same as word_list_to_check_for_comment but for word shorter than 6 characters
short_word_list_to_check_for_comment:
  - "com"
  - "quel"
  - "quelle"

# Those are the word needed on the tweet for the bot to tag one or more account
word_list_to_check_for_tag:
  - "invit"
  - "mention"
  - "mentionnez une"
  - "mentionnez un"
  - "mentionnez des"  
  - "tag"
  - "#tag"
  - "taguer"       
  - "identif"
  - "notifie"
  - "@ un"
  - "@ une"
  - "@ des"
  - "@ tes"
  - "@ 1"
  - "@ deux"
  - "@ 2"
  - "@ plusieurs"
  
# Word list to check if we need to tag 1 account
one_poeple_list:
  
  - "@ un"
  - "@ 1"
  - "tag un"
  - "tag 1"
  - "mentionne 1"
  - "mentionne un"
  - "mentionne ton"
  - "mentionne ta"
  - "mentionne le"
  - "invite 1"
  - "inviter 1"
  - "inviter un"
  - "inviter ton"
  - "inviter ta"
  - "inviter le"
  - "invite un"
  - "invite ton"
  - "invite ta"
  - "invite le"
  - "invite un"
  - "invite ton"
  - "invite ta"
  - "invite le"
  - "tag ton"
  - "tag ta"
  - "tag la"
  - "tag le"
  - "un ami"
  - "un copain"
  - "une personne"
  - "un mate"
  - "une mate"
  - "un(e) mate"
  - "la personne"
  - "votre pote"
  - "votre ami"
  - "un pote"
  - "1 pote"
  - "1 am.i.e "
  - "1 ami"
  - "1 copain"
  - "1 personne"
  - "un(e) ami(e)"
  - "une(e) ami(e)"
  - "un.e ami.e"
  - "tag quelqu'un"
  - "taguez quelqu'un"
  - "un fan"
  - "un(e) fan"
  - "1 fan"
  - "un(e) pote"
  - "ton pote"
  - "ta pote"
  - "ton ami"
  - "ton copain"
  - "un/une ami"
  - "un/une pote"
  - "un•e ami•e"
  - "un(e) pote"
  - "mentionne quelqu'un"
  


# Word list to check if we need to tag 2 accounts
two_poeple_list:
  - "tag deux"
  - "tag 2"
  - "@ deux"
  - "@ 2"
  - "2 amis"
  - "tes amis"
  - "tes potes"
  - "2 ami(e)s"
  - "2 ami"
  - "2 personnes"
  - "2 potes"
  - "des potes"
  - "tes potes"
  - "ses potes"
  - "deux amis"
  - "deux ami(e)s"
  - "deux ami"
  - "deux personnes"
  - "deux potes"

# Word list to check if we need to tag 3 accounts or more
three_or_more_poeple_list:
  - "3 amis"
  - "3 ami(e)s"
  - "3 ami"
  - "3 personnes"
  - "3 potes"
  - "trois amis"
  - "trois ami(e)s"
  - "trois ami"
  - "trois personnes"
  - "trois potes"
  - "tes amis"
  - "des amis"
  - "tes potes"
  - "des potes"


# Sentences you need to tweet to invite a friend you must but a space at the end of each sentence
sentence_for_tag:
  - "J'invite : "
  - "Merci ! je tag : "
  - "Je tag : "
  - "Hop Hop, j'invite : "
  - "Avec moi : "
  - "Help me : "
  - "Pour vous aussi les gars : "
  - "tentez votre chance ! "
  - "Je tente ma chance ! J'espère que je vais gagner ! "
  - "J'espère que vais gagner ! "
  - "Merci pour le concours ! Essayez aussi : "
  - "Que la chance soit avec moi ! et vous "
  - "Merci d'organiser ce concours ! Ça peut vous intéresser "
  - "On croise les doigts ! vous aussi "
  - "C'est pour vous ça ! : "
  - "Celui là on le gagne"
  - "J'espère que vais gagner ! On participe ! "
  - "Merci d'organiser ce concours ! "
  - "Bonne chance à tous ! "
  - "J'adore les concours et je sais que vous aussi "
  - "J'ai tellement envie de gagner, essayez vous aussi "
  - "Je participe et j'invite "
  - "Bonjour je participe avec plaisir. Merci pour ce concours et bonne journée ! "
  - "Merci beaucoup j'adore votre compte. Je vous souhaite une belle continuation. J'invite "
  - "Bonjour je participe avec plaisir à ce super concours et j'invite "
  - "Superbe ! Je tente ma chance bien volontiers et j'invite "
  - "Chouette bonjour je participe avec plaisir avec "
  - "Bonjour je tente ma chance avec "
  - "Bonjour, Je tente ma chance bien volontiers et j'invite "
  - "Merci beaucoup pour ce super concours, je tague "
  - "Bonjour génial ! Je tente ma chance et j'identifie "
  - "Merci ! J'invite "
  - "Hello !!! Merci beaucoup je tente ma chance merci et bonne journée ! Je tague "
  - "Bonjour je participe avec plaisir pour ce beau cadeau et j'invite "
  - "Bonjour et merci pour ce super concours :) j'invite "
  - "Bonjour, trop Sympa ce concours. Essayez-vous aussi "
  - "Je tag mes amis "
  - "On tente encore et encore "
  - "Je tente ma chance aux côtés de "
  - "Incroyable concours merci beaucoup "
  - "Qu'est ce que vous en pensez ? Allez participez-vous aussi "
  - "Let's go, je suis sûr qu'on va gagner cette fois :) "

# Sentences you need to tweet when you need to do a comment but don't need to invite friend you must but a space at the end of each sentence
sentence_for_random_comment:
  - "Merci ! "
  - "Je participe "
  - "Hop Hop "
  - "Que la force soit avec moi "
  - "Je tente ma chance ! J'espère que je vais gagner ! "
  - "J'espère que vais gagner ! "
  - "Merci pour le concours ! "
  - "Que la chance soit avec moi ! "
  - "Merci d'organiser ce concours ! "
  - "On croise les doigts ! "
  - "C'est pour moi ça ! "
  - "Celui là on le gagne"
  - "J'espère que vais gagner ! Je participe ! "
  - "Merci d'organiser ce concours ! "
  - "Bonne chance à tous ! "
  - "J'adore les concours et surtout celui si "
  - "J'ai tellement envie de gagner "
  - "Bonjour je participe avec plaisir. Merci pour ce concours et bonne journée ! "
  - "Merci beaucoup pour ce concours j'adore votre compte. Je vous souhaite une belle continuation "
  - "Merci beaucoup pour cette opportunité !"
  - "Je me lance, je participe avec enthousiasme."
  - "Hop Hop, prêt pour l'aventure !"
  - "Que la chance soit de mon côté cette fois-ci."
  - "Je tente ma chance et croise les doigts pour la victoire !"
  - "Merci pour cette chance de gagner !"
  - "Espoir et optimisme, que la chance soit avec moi !"
  - "Un grand merci pour l'organisation de ce concours !"
  - "Je croise les doigts et espère une pluie de chance !"
  - "Participer, c'est déjà une victoire en soi !"
  - "Celui-ci est pour moi, j'en suis convaincu !"
  - "C'est le concours à ne pas rater, je tente ma chance !"
  - "J'espère décrocher la victoire, je participe avec plaisir !"
  - "Bonne chance à tous les participants !"
  - "J'apprécie vraiment les concours, et celui-ci semble génial !"
  - "L'envie de gagner est grande, je fonce !"
  - "Salut ! Participation confirmée, merci pour cette opportunité !"
  - "Votre compte est fantastique, merci pour ce concours !"
  - "Je suis partant pour ce super concours, merci !"
  - "Magnifique ! Je tente ma chance avec optimisme !"
  - "Bonjour ! Participation avec enthousiasme, merci !"
  - "Je tente ma chance, croisons les doigts !"
  - "C'est une occasion à ne pas manquer, je participe !"
  - "Merci beaucoup pour cette chance, je suis partant !"
  - "Hello, je m'engage dans cette aventure, merci !"
  - "Je participe avec joie pour ce beau cadeau !"
  - "Merci infiniment pour ce concours, je tente ma chance !"
  - "Bonjour et merci pour cette opportunité, je participe !"
  - "Trop sympa ce concours, je suis partant !"
  - "On continue à tenter sa chance, c'est le jeu !"
  - "J'espère que la chance sera de mon côté, je participe !"
  - "Incroyable concours, merci pour cette opportunité !"
  - "Let's go, confiant que la victoire sera au rendez-vous !"
  - "Je participe avec espoir et gratitude, merci !"
  - "L'aventure du concours commence, je suis prêt !"
  - "Merci pour cette chance de gagner, je participe !"
  - "C'est parti, je tente ma chance avec optimisme !"
  - "J'adore participer à des concours, et celui-ci est top !"
  - "On ne sait jamais, je tente ma chance avec espoir !"
  - "Merci pour cette opportunité, je participe avec enthousiasme !"
  - "Je participe avec le sourire, merci pour ce concours !"
  - "Que la chance soit avec tous les participants !"
  - "Un grand merci pour l'organisation, je tente ma chance !"
  - "C'est pour moi une occasion à ne pas manquer, je participe !"
  - "Merci beaucoup pour ce concours, je tente ma chance !"
  - "Bonne chance à chacun, je participe avec plaisir !"
  - "Bonjour je participe avec plaisir à ce super concours "
  - "Superbe ! Je tente ma chance bien volontiers "
  - "Chouette bonjour je participe avec plaisir "
  - "Bonjour je tente ma chance "
  - "Bonjour, Je tente ma chance bien volontiers "
  - "Merci beaucoup pour ce super concour "
  - "Bonjour génial ! Je tente ma chance "
  - "Hello !!! Merci beaucoup je tente ma chance "
  - "Bonjour je participe avec plaisir pour ce beau cadeau "
  - "Bonjour et merci pour ce super concours :) "
  - "Bonjour, trop Sympa ce concours. "
  - "On tente encore et encore "
  - "Je tente ma chance même si je risque de ne pas gagner "
  - "Incroyable concours merci beaucoup "
  - "Let's go, je suis sûr de gagner cette fois :) "
  - "Je participe à ce magnifique concours"
  - "Miam"
  - "Super cadeau !"
  - "Bonjour, Merci pour ce concours"
  - "Je tente, ils sont trop bons"
  - "Beau cadeau !"
  - "Oh punaise"
  - "Coucou, je participe, merci"
  - "Je tente ma chance"
  - "Je tente ma chance merci pour le concours"
  - "Bonne chance à tous !"
  - "merci"
  - "Oh jolie"
  - "Je tente merci bcp"
  - "Très beau concours !!!"
  - ":)"
  - "Je participe"
  - "Je commente ce post !"
  - "J'ajoute mon commentaire"
  - "Bonjour, je participe."
  - "je tente avec plaisir, merci"
  - "je croise les doigts"
  - "Merci pour le concours et je l'offrirai à maman"
  - "Grande fan je tente merci pour le concours !!! :-)"
  - "Top"
  - "Allez !"
  - "Merci pour ce concours"
  - "Allez je tente"
  - "Pour ma petite maman"
  - "Merci beaucoup pour ce concours"
  - "Je tente ma chance merci !"
  - "Waouhhhh je tente ma chance avec gourmandise"
  - "J'aime !"
  - "Ohh je tente"
  - "Merciiii"
  - "Bonjour,je participe. Bonne journée"
  - "Je tente !!"
  - "je participe merci"
  - "Merci pour le concours, je participe avec plaisir."
  - "ce post"
  - "Super merci"
  - "Miam, miam j'en veux"
  - "Miiiuaaaaaam"
  - "Il a l'air trop bien"
  - "Trop bien je tente"
  - "Oh Yeah Bonne chance à tous !"
  - "Merci pour le concours"
  - "j'espere gagner ce concours mdr"
  - "Lets go"
  - "Ca serait super !"
  - "Bonsoir, merci pour ce superbe concours, bonne chance et bonne soirée."
  - "Merci !"
  - "Excellent"
  - "Bonne chance à tous ! *croise les doigts dans son dos*"
  - "J’espère gagner ce concours s’il vous plaît bonne chance à tous dit"
  - "Je tente ma chance . Merci"
  - "moi moi moi :p"
  - "Pour donner une dernière chance à la licence "
  - "On va tenter on sait jamais"
  - "Merci de nous gâter "
  - "Bonne chance"
  - "prout"
  - "Merci pour le concours :)"
  - "Oh bon Dieu"
  - "Qui ne tente rien n’a rien"
  - "Je tente ma chance "
  - "Bonjour je participe avec plaisir"
  - "Shay a dit je crée ma propre chance alors lets go"
  - "Merci pour ce petit concours et bonne chance à tout le monde "
  - "Merci, je participe, hâte !"
  - "Merci pour le concours! "
  - "Je participe ! bonne chance à tous !"
  - "Merci pour le concours !"
  - "Merci pour le concours"
  - "Thanks so much "
  - "wow!"
  - "Merci bcp! ^^ "
  - "Merci pour l'opportunité! "
  - "Bonne chance à tous! "
  - "Merci pour ce concours, je participe avec plaisir"
  - "Ceci est un commentaire dans l'espoir de gagner. Merci pour ce concours."
  - "Merci beaucoup pour ce concours je participe avec plaisir "
  - "Merci pour ce concours je croise les doigts "
  - "Je croise les doigts, merci pour le concours !"
  - "J’adore "
  - "Je participe merci "
  - "Thank u :)"
  - "Bonjour trop bien je tente ma chance "
  - "merci BEAUCOUP pour ce concours"
  - "Oh oui oui oui !!! "
  - "Merci pour cette opportunité!"
  - "je participe !"
  - "Merci beaucoup "
  - "Je tente ma chance merci "
  - "Oh trop bien !!! Merci pour le concours !! Je participe avec plaisir"
  - "On tente "
  - "Yey"
  - "Let's go ! "
  - "je participe :)"
  - "Ouah excellent merci beaucoup "
  - "merciiii !"
  - "Super je participe on verra bien si je gagne."
  - "Merci pour votre concours"
  - "je veux"
  - "Je tente merci "
  - "Merci pour ce concours on croise les doigts  "
  - "Merci pour ce concours,  je participe "
  - "Je participe ! Merci beaucoup pour le concours ! "
  - "Qui ne tente rien, n'a rien ! Allez j'essaye."
  - "Encore un concours auquel je participe en sachant que je gagnerai pas"
  - "Ce serait top !!"
  - "Bonjour, Je tente ma chance avec grand plaisir merci"
  - "Bonjour, je participe  merci"
  - "Bonjour merci pour ce magnifique cadeau"
  - "Je participe.  Mille mercis"
  - "Bonjour, super merci beaucoup pour le concours"
  - "Je participe merci  "
  - "Merci bien"
  - "Bonjour, Je tente ma chance avec grand plaisir Merci"
  - "Bonjour, je participe avec plaisir merci "
  - "Bonne chance à tous"
  - "Kikoooo je tente ma chance avec grand plaisir merci"
  - "Bonjour, je tente... merci pour ce concours. "
  - "Espérons "
  - "Merci pour ce concours et bonne chance à tous "
  - "waouh c'est un magnifique ce cadeau que vous nous faite merci belle journée"
  - "Je compte sur vous "
  - "Je compte sur moi et ma chance"
  - "Je compte sur moi et ma chatte"
  - "Si seulement"
  - "Bonne chance !"
  - "Bonjour, je croise les doigts "
  - "Je tente volontiers"
  - "On croise les doigts "
  - "Oh pitié"
  - "Bonjour super concours merci a vous, je participe "
  - "Je participe en bienbien"
  - "C'est pour moi ça"
  - "Je participe !"
  - "youhouuu mercii"
  - "Bonjour trop cool je participe, merci beaucoup pour ce sublime gain "
  - "Bonne chance à moi une chance dans le monde "
  - "Merci à vous ! Je participe !"
  - "Wow merci je participe avec plaisir "
  - "J'aimerais bien gagné mais ça risque pas ..."
  - "Bonne chance à toutes et à tous "
  - "J’espere gagné bonne chance à tout le monde"
  - "Allez"
  - "Bonjour je participe merci beaucoup"
  - "Nice"
  - "Allez c’est pour moi"
  - "Bonjour, je participe pour ce superbe concours  Merci à vous "
  - "Sympa je souhaite participer merci beaucoup"
  - "Le top du top ! Je croise les doigts "
  - "Bonne chance tt le monde "
  - "Why nooot "
  - "je participe!!"
  - "Il sera parfait "
  - "Bonjour et merci beaucoup! J'en aurai vraiment besoin donc on croise les doigts "
  - "Why nooot "
  - "Je tente ma chance on verra bien"
  - "J'espère je gagne c'est ma marque pref "
  - "Gl à tous"
  - "Incroyable merci !! "
  - "On va tester on sait jamais"
  - "Trop bien merci !"
  - "Participation à ce super concours"
  - "Merci pour le concours il est top"
  - "Done"
  - "Let’s go"
  - "Carre le concours"
  - "Top le concours"
  - "Mon rêve de gagner"
  - "go gagner !"
  - "j espères le gagner"
  - "Lets gooooo"
  - "Bonne chance ^^"
  - "On espère on espère"
  - "ici c'est paris"
  - "Aller on y croit ;)"
  - "Fait maintenant on croise les doigts "
  - "Trop bien"
  - "on croise les doigts"
  - "J’aimerais trop gagner"
  - "Ptn j’espère"
  - "Allez on y croit"
  - "On tente le coup "
  - "j'tente ma chance alors qu'on sait tous que j'vais pas gagner"
  - "P'tit banger"
  - "Il est beau celui la :)"
  - "Incroyable je croise les doigts "
  - "Je participe avec le plus grand des plaisirs en espérant gagner"
  - "Incroyable je croise les doigts "
  - "Merci"
  - "Svp"
  - "Bonne chance les frères !"
  - "Bonne chance à tous et toutes !!!"
  - "On croise les doigts !"
  - "Magnifique "
  - "J'ai hâte du TAS !"
  - "Non la c'est la bonne je jure"
  - "O wow "
  - "Weeeeee!!"
  - "il y a pas de hasard il y a que Eden Hazard"
  - "svp moi"
  - "shiesh"
  - "Incroyableeeee"
  - "merci vous vous régalez"
  - "yessss encore un concours pour moi ça !!!"
  - "Let'go"
  - "J’espère "
  - "Moi !!"
  - "bonne chance tout le monde"
  - "Aller un peu de chance j espère"
  - "J'espère mais j'ai pas espoir"
  - "Les affaires sont les affaires"
  - "Incroyable "
  - "On sait jamais"
  - "On y croit ! (oupas) "
  - "Lets go "
  - "allez je participe on sait jamais bonne chance a tous "
  - "!!"
  - "Merci beaucoup, on va tenter. "
  - "svp me"
  - "Je participe! "
  - "je tente ma chance pour ce super méga cadeau d'enfer "
  - ". Bien. Commencons"
  - "Alors la Merci"
  - "Je voudrais trop gagné "
  - "Trop bien le concours"
  - "Je tente ma chance "
  - "OH trop bien ! Bonne chance tout le monde !"
  - "On tente meme si j'ai peu de chance de gagner"
  - "On tente sa chance"
  - "On tence sa chance par ici"
  - "je tente ma chance"
  - "J’aimerais bien  gagner"
  - "trop bien merci pour ce joli concours"
  - "Alley, pourquoi pas ! On ne sait jamais "
  - "Bonjour je participe merci "
  - "Lets gooo "
  - "hello, je participe ! ! :)"
  - "Bonjour je participe avec plaisir merci"
  - "trop bien merci pour ce jeu concours"
  - "sans trop y croire mais avec le hasard..."
  - "je participe tu participes il participe merci beaucoup"
  - "Lets goo"
  - "si seulement je pouvais gagner"
  - "merci pour ce cadeau  "
  - "moi !!!"
  - "Merci pour tout ces concours si je gagne je serai trop content"
  - "Merci pour votre jeux concours  "
  - "je participe en légende hehehe"
  - "Je vais gagner"
  - "Merci je participe"
  - "Bonne chance les garssss"
  - "Gg"
  - "Gl"
  - "Et pourquoi pas !"
  - "goo"
  - "mici "
  - "Cool"
  - "GL "
  - "mercii je participe"
  - "Bonne chance !! "
  - "Merci à toi "
  - "pour mon moi ça"
  - "j'espére gagné ..."
  - "j'espére gagné"
  - "Yeeeees"
  - "Peut être"
  - "Peut être que"
  - "La chance va peut être me sourir aujourd'hui"
  - "Aller bonne chance à tous"
  - "quel beau cadeau merci beaucoup pour ce concours,je tente ma chance avec plaisir"
  - "elle est super belle en noir :)"
  - "Trop bien merci !! "
  - "merci beaucoup"
  - "Merci pour le concours. Je tente ma chance ! "
  - "Impeccable merci "
  - "OUUI"
  - "Trop bien je serais ravie de l'accueillir merci "
  - "Le rêve "
  - "Allez ça tente sa chance ici"
  - "Jean rêve"
  - "Merci pour le concours !  Je tente ma chance …"
  - "Super sympa le petit concours qui fait plaiz"
  - "Dinguerie le concours"
  - "Trop cool "
  - "Vasy on tente on croise les doigts"
  - "Good luck les gens "
  - "Je participe avec plaisir."
  - "On tente le coup"
  - "Super cool"
  - "Super Mega cool"
  - "bonne chance à nous"
  - "et siii"
  - "un commentaire de plus sur insta"

  
# If headless is set to True the bot won't open a chrome windows while doing giveaways otherwise it will
headless: True

#If the option is set to False the bot will only @ account withouth the sentence when he need to
add_sentence_to_tag: False
