# Instagram account email/username

account_email_or_username: "s.fzefzefzefezfzefzefdjfdsofjdsoifsdf@gmail.com"

# Instagram account password

account_password: "sdfsdftefzefzeefzefzefdsfdsfkposdfkpveezfzefdsfn1"